### ISSUE TITLE
希望能支持本地播放

### ISSUE THREAD

**Issue by xiaowenlv** [eprendre/tingshu#10]
之所以有这样的需求是因为下载了很多小说又没有一款能支持m4a又能倍速播放的好工具，枫叶播放器虽然很好但是太久不更新只支持MP3

**Comment by eprendre** [comment]
本地播放有一款很优秀的开源播放器，专门用来播放有声读物的：
https://github.com/PaulWoitaschek/Voice/releases 。别人有这个需求我也是安利这个。

**Comment by xiaowenlv** [comment]
@eprendre 你说的那款支持倍速吗，另外能否加上显示小说已更新到多少张、章节倒叙或者翻页功能，现在的小说都是几百上千张的，一点点往后翻实在太慢。有个网站虽然能搜到的书是最多的，但每次放出来都是请五分钟后再访问的提示，这个有办法吗？其实软件已经很强了，希望越来越强大。

**Comment by xiaowenlv** [comment]
@eprendre 你推荐的那款太奇葩了，居然只能一张一张的切，手动选择的章节不会播放。

**Comment by eprendre** [comment]
> @eprendre 你推荐的那款太奇葩了，居然只能一张一张的切，手动选择的章节不会播放。

我试过完全没问题啊，可以随便选来播放。不知道是不是你的音频文件有问题。
我还用这个播放器来播放m4b的有声读物，很完美。/(ㄒoㄒ)/~~

**Comment by xiaowenlv** [comment]
@eprendre 没问题啊，就是普通的音乐，我是先导入一个文件夹然后播放的，就只能一张张切，从列表里选的不会播放

**Comment by eprendre** [comment]
o(╥﹏╥)o 关了关了，确定不会支持。
