### ISSUE TITLE
有时候在锁频界面点击播放后放一会就回自动暂停是怎么回事？

### ISSUE THREAD

**Issue by QingShui23** [eprendre/tingshu#13]
手机是mate30pro，
有时候一段时间没听后，解锁手机在锁屏界面点击播放后会，播放一段时间后自动停止。如果想继续听就得解锁进入app重新点击播放按钮才能正常连续播放。

**Comment by QingShui23** [comment]
另外，播放有时候要点击两次能播放，貌似不是预解析的？

**Comment by eprendre** [comment]
我也是mate 30 pro，锁屏问题一般给app加个锁就可以解决，实在不行去加后台白名单。我貌似用久了，现在都不加也没问题。

第二个问题确实不是预解析，我怕某些网站返回的音频地址有失效时间。但播放按钮我一直都是点一次就行，是不是你用的那个源速度太慢了。其实你可以去设置开启自动缓存，体验会好许多。

**Comment by lhl-012** [comment]
我也遇到了，只有亮屏才能继续播放，感觉应该是下载或者播放得某些部分代码锁屏下无法执行

**Comment by eprendre** [comment]
> 我也遇到了，只有亮屏才能继续播放，感觉应该是下载或者播放得某些部分代码锁屏下无法执行

是的，播放下集时的音频播放地址是实时获取的，可能就是这部分的操作被锁屏给掐住了。通过我手头的几台设备测试下来，加锁加后台白名单可以解决。
