### ISSUE TITLE
手机是按键安卓的，不能触屏！无法选择播放，

### ISSUE THREAD

**Issue by tyzcxbl** [eprendre/tingshu#14]
手机是按键安卓机，不能触屏。喜欢听书😍，试了一下，无法选择到播放的小说上，希望能增加方向键选择功能！

**Comment by eprendre** [comment]
这个问题我在安卓电视上使用时也发现了。我当时也想着能不能优化，但是后来感觉有些界面的逻辑和方向键有冲突，不好改。目前电视上可以连个蓝牙鼠标解决，倒是你这个按键安卓机着实少见诶。

**Comment by eprendre** [comment]
最新版已经支持纯遥控操作了，按键应该同理。
