### ISSUE TITLE
这个APP怎样跟蓝牙音响连接呢？

### ISSUE THREAD

**Issue by murongmingrui** [eprendre/tingshu#15]
这个APP怎样跟蓝牙音响连接呢？如果能用蓝牙音响听书就好了

**Comment by murongmingrui** [comment]
另外，如果能自己添加音频源就好了

**Comment by eprendre** [comment]
连蓝牙和app无关，手机设置里连上蓝牙打开app即可播放。
添加源这个我技术有限暂时做不来，不过你可以推荐网站，我觉得合适的话会添加的。
