### ISSUE TITLE
建议添加一个听书源

### ISSUE THREAD

**Issue by murongmingrui** [eprendre/tingshu#16]
https://audiomack.com/search   可能需要翻才能进入网站。资源不少，还有不少儿童不宜资源，比如叶倩彤的白洁之类的

**Comment by eprendre** [comment]
这网站的页面逻辑和那些听书站不太一样，不一定好加进来，我试试看吧。

**Comment by eprendre** [comment]
我评估了一下，这个网站加起来貌似很难啊，先放弃😿
