### ISSUE TITLE
请求添加源

### ISSUE THREAD

**Issue by Kevin0Jung** [eprendre/tingshu#19]
请求添加源:22听书网
https://m.ting22.com
有很多优质资源，喜马拉雅上面付费的也有，可以免费听，请求大佬添加🙏🙏🙏

**Comment by eprendre** [comment]
这网站以前曾经加过，但是我们用户多啊，站长跑过来说服务器压力太大，于是我就去掉了。如果想加回去要得到站长的同意才行，你们看看有啥好解决的方法？比如给站长捐赠？但我相信大部分人是白嫖党，不愿意这么做的。
