### ISSUE TITLE
请求在通知栏右边添加退出程序按钮

### ISSUE THREAD

**Issue by huqichun** [eprendre/tingshu#2]
如题，希望大佬能考虑下，在某些紧急情况下，快速结束程序

**Comment by eprendre** [comment]
其实暂停一下就可以划掉通知了

**Comment by eprendre** [comment]
我去看了一下代码，发现已经写上添加关闭按钮的代码了。但是为什么在我们手机上都没显示呢？ https://stackoverflow.com/a/26947636 参考这里，安卓 5.0 之前才会出现这个按钮，在 5.0 之后我们需要先暂停一下音频，再自己划掉它。
