### ISSUE TITLE
最新版闪退

### ISSUE THREAD

**Issue by CubieHuang** [eprendre/tingshu#22]
Oneplus 5T  H2OS：5.1.2 我的听书 v1.7.2 闪退

**Comment by eprendre** [comment]
app用了360加固，我发现最近这个加固有所改动，导致部分低版本的安卓系统不兼容。但是我又不可能把加固去掉，毕竟令人恶心的家伙太多了，拿着你的app乱改，报错全部传给我的bug统计那边。
