### ISSUE TITLE
反馈一个书源失效问题，提一个自动备份功能建议

### ISSUE THREAD

**Issue by LiteCoder** [eprendre/tingshu#24]
首先感谢开发了很好用的听书app，主要提一个功能建议
1、云图有声书源失效了，搜索失败
2、升级到2.0版本时选择了内置升级（之前一直是用外置升级的，这次误操作点了内置升级），桌面出现两个app图标；然后下载app安装包覆盖安装后桌面一个图标也没有了，系统是emui9.1；在应用管理里卸载后重装恢复正常了，但登录坚果云后发现收藏还是没有，这是才发现是需要手动备份的。。。所以建议增加一个收藏自动备份的功能。

**Comment by eprendre** [comment]
云图有声我这里都是好的，可能你搜的特定关键词失败了。
图标消失重启手机即可。
以前做过自动备份，但是多台设备同时登录会出问题。

**Comment by LiteCoder** [comment]
感谢解答，看来以后有问题重启下先；
再次试了云图有声不能加载是网络问题，联通的4G网络 提示加载出错，联网上wifi后正常了
