### ISSUE TITLE
按照操作步骤进行打jar包，发现jar包里是空的

### ISSUE THREAD

**Issue by luyou2019** [eprendre/tingshu#27]
![1](https://user-images.githubusercontent.com/54252871/103739957-5a16df00-5031-11eb-926e-5cf356d25f9e.png)

**Comment by eprendre** [comment]
这个空是指文件为 0KB 还是说解压打开里面看不到代码？

**Comment by luyou2019** [comment]
![mmexport1609917971773](https://user-images.githubusercontent.com/54252871/103741144-85023280-5033-11eb-8a02-d8b05e9117f4.png)
里面没有class文件

**Comment by luyou2019** [comment]
解压看不到代码



---原始邮件---
发件人: "eprendre"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 下午3:20
收件人: "eprendre/tingshu"<tingshu@noreply.github.com&gt;;
抄送: "陆游"<1394197274@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [eprendre/tingshu] 按照操作步骤进行打jar包，发现jar包里是空的 (#27)




 
这个空是指文件为 0KB 还是说解压打开里面看不到代码？

**Comment by eprendre** [comment]
那完全没问题。。。代码被打包到dex里了
