### ISSUE TITLE
爬取海洋听书网的音频文件来自于有声小说网站，这种情况怎么解决？

### ISSUE THREAD

**Issue by luyou2019** [eprendre/tingshu#28]
这是音频文件的路径：http://ysting.ysxs8.com:81/%E5%AE%98%E5%9C%BA%E5%88%91%E4%BE%A6/%E3%80%8A%E7%A6%8F%E5%B0%94%E6%91%A9%E6%96%AF%E4%B9%8B%E7%AC%AC%E4%BA%8C%E5%9D%97%E8%A1%80%E8%BF%B9%E3%80%8B/%E3%80%8A%E7%A6%8F%E5%B0%94%E6%91%A9%E6%96%AF%E4%B9%8B%E7%AC%AC%E4%BA%8C%E5%9D%97%E8%A1%80%E8%BF%B9%E3%80%8B001--%E6%9C%89%E5%A3%B0%E5%B0%8F%E8%AF%B4%E5%90%A7[www.ysxs8.com].mp3
这个指向有声小说网，而且有声小说网有反爬，在app内获取到该路径但不能播放，能解决吗？
![1](https://user-images.githubusercontent.com/54252871/103752280-7b34fb00-5044-11eb-9994-f8ba3da8abef.png)
![2](https://user-images.githubusercontent.com/54252871/103752284-7c662800-5044-11eb-98ee-26066efc9603.jpg)

**Comment by eprendre** [comment]
缺少请求头（Headers），播放器在播放音频地址时会自动加上UserAgent，但是其它header如果缺少的话得自己添加，比如你这个链接缺少的可能是 Referer。实现 AudioUrlExtraHeaders 即可，你可以参考这里：https://github.com/eprendre/tingshu/blob/679280a5817574d46e51d239b62e8dc3f1538b24/CustomSources/src/main/kotlin/com/github/eprendre/sources_by_eprendre/KouDaiWeiKeTang.kt

**Comment by eprendre** [comment]
先用浏览器查看相关的请求头，再用诸如postman之类的工具调试以找到必须的header。
![1](https://user-images.githubusercontent.com/7194531/103756638-a7537a80-504a-11eb-8072-0e295c300374.jpeg)
![2](https://user-images.githubusercontent.com/7194531/103756652-ab7f9800-504a-11eb-80f4-fa5f86aeddf0.jpg)
![3](https://user-images.githubusercontent.com/7194531/103756662-ade1f200-504a-11eb-9af3-6df3a6d984c3.jpg)
