### ISSUE TITLE
不展示网站图片，通过postman测试发现图片请求header需要添加host，实现如下方法依然不展示图片

### ISSUE THREAD

**Issue by luyou2019** [eprendre/tingshu#30]
![4](https://user-images.githubusercontent.com/54252871/104151967-4694bb00-5419-11eb-89f0-6382067b9295.jpg)
![3](https://user-images.githubusercontent.com/54252871/104151976-4d233280-5419-11eb-8324-4e9f1ba9d9f1.png)
![2](https://user-images.githubusercontent.com/54252871/104151982-50b6b980-5419-11eb-8835-0d680c212d10.png)
![1](https://user-images.githubusercontent.com/54252871/104151987-53b1aa00-5419-11eb-80c3-6adafc23c2da.png)

**Comment by eprendre** [comment]
代码这样写很危险，会把其它所有源的封面都加上这个Host了。参考这个：
```kotlin
    override fun coverHeaders(coverUrl: String, headers: MutableMap<String, String>): Boolean {
        if(coverUrl.contains("2uxs.com") || coverUrl.contains("xinexin.cn")) {
            headers["Referer"] = "http://www.2uxs.com/"
            headers["Host"] = URL(coverUrl).host
            return true
        }
        return false
    }
```
具体原因我晚些时候回去看一下

**Comment by luyou2019** [comment]
加上了也没有用，这是图片地址：http://www.ysxs8.com/pic/uploadimg/2015-7/20157713535867029.jpg
![5](https://user-images.githubusercontent.com/54252871/104156538-3930fe00-5424-11eb-9f17-1b1fae28fa92.png)

**Comment by eprendre** [comment]
原因找到了，有声小说吧屏蔽了手机的UA（所有图片会默认加上这个UA），用代码改成桌面UA即可：
```kotlin
    override fun coverHeaders(coverUrl: String, headers: MutableMap<String, String>): Boolean {
        if(coverUrl.contains("ysxs8.com")) {
            headers["Host"] = URL(coverUrl).host
            headers["User-Agent"] = getDesktopUA()
            return true
        }
        return false
    }
```

**Comment by luyou2019** [comment]
图片问题已经解决。但是音频还是有问题，我在postman上添加Referer或Cookie都行，但是在软件上还是无法播放，然后试着添加User-Agent也没有效果，音频地址是：http://ysting.ysxs8.com:81/%E6%8E%A2%E9%99%A9%E7%9B%97%E5%A2%93/%E3%80%8A%E9%AC%BC%E5%90%B9%E7%81%AF%E7%AC%AC2%E9%83%A81%E5%8D%B7%E9%BB%84%E7%9A%AE%E5%AD%90%E5%9D%9F%E3%80%8B%E8%89%BE%E5%AE%9D%E8%89%AF/%E3%80%8A%E9%AC%BC%E5%90%B9%E7%81%AF%E7%AC%AC2%E9%83%A81%E5%8D%B7%E9%BB%84%E7%9A%AE%E5%AD%90%E5%9D%9F%E3%80%8B001--%E6%9C%89%E5%A3%B0%E5%B0%8F%E8%AF%B4%E5%90%A7[www.ysxs8.com].mp3
以下是postman、浏览器和程序代码截图：
![3](https://user-images.githubusercontent.com/54252871/104265365-60410b80-54c8-11eb-8df3-ac237daf824c.png)
![1](https://user-images.githubusercontent.com/54252871/104265391-7353db80-54c8-11eb-8590-608f1ea9f72b.png)
![2](https://user-images.githubusercontent.com/54252871/104265396-764ecc00-54c8-11eb-91a6-0fdee0126153.png)
![4](https://user-images.githubusercontent.com/54252871/104265821-671c4e00-54c9-11eb-9864-fb1c1c7370e3.png)

**Comment by eprendre** [comment]
https://github.com/eprendre/tingshu/blob/master/CustomSources/src/main/kotlin/com/github/eprendre/sources_by_eprendre/YouShengXiaoShuoBa.kt
这是我的示例代码，有声小说吧用了iframe嵌套，需要修改script才能获取到内部iframe的元素。

**Comment by eprendre** [comment]
原因找到了： PC版页面对音频地址做了验证， 需要加上Cookies。 而我那个代码是手机版的，它的音频地址带上了一个参数： vsid=xxxxxx，免去了验证。

**Comment by luyou2019** [comment]
在app 里没法调试，因为app调试获取的第一本书音频文件，在原网站上这本书音频文件就是没有的，所以app上调试不出来。我把代码发给你吧，我有二群和三群，怎么发给你。

**Comment by eprendre** [comment]
问题已解决
