### ISSUE TITLE
建议加个交流社区

### ISSUE THREAD

**Issue by lunhuil** [eprendre/tingshu#31]
比如免费的兔小巢，方便交流，分享
https://txc.qq.com/
还有消息提醒接口，被回帖能看到提示

**Comment by eprendre** [comment]
以前加过，而且我每条信息都看。但是用户基数多了，傻逼也随之变多。举个例子：喜马拉雅不能听收费的就跑来骂垃圾。源网站不稳定反而怪我收录了那个源。还有一些专门来恶心我的。
