### ISSUE TITLE
webdav问题

### ISSUE THREAD

**Issue by leonwahy** [eprendre/tingshu#33]
webdav设置后不能识别二级目录，只能放在一级目录下方可识别并播放。求更新解决。谢谢！

**Comment by eprendre** [comment]
首先请先了解一下路径层级的约定，然后webdav设置里有一个（有声书目录设置）可以指定路径，比如：aaaa/bbbb/ccc/我的听书。指定一下路径不管放到第几级都没问题。

**Comment by leonwahy** [comment]
感谢您的答复，目前已经设置我的路径，只是不能识别听书文件夹的二级目录。
比如目前文件夹是：书籍/书名/版本/实际文件，所以就遇到了实际文件无法播放（直接点击“书名”文件夹不能打开到版本文件夹，只能选择“收藏、播放”等功能），而如果将“版本”文件夹直接放到“书籍”文件夹下面就可以识别并播放。
致谢！

**Comment by eprendre** [comment]
约定就是这样的：'听书根目录/分类目录/书籍目录' 。考虑到效率以及音频文件名排序问题，书籍下面只扫描当前目录的音频文件，不遍历子文件夹。

**Comment by leonwahy** [comment]
好的，已知。目前已在使用，谢谢！
目前也能使用，只需要全部按照此规则调整方可。
感谢开发如此好用的应用，谢谢！
