### ISSUE TITLE
请问Fuel这个库是否支持http/2，在做一个源，发现网站貌似只支持http2

### ISSUE THREAD

**Issue by yimik** [eprendre/tingshu#34]
对Android开发不了解，查了半天，貌似只查到okhttp支持

**Comment by eprendre** [comment]
implementation 'com.squareup.okhttp3:okhttp:4.7.2'

在gradle里面引用okhttp，理论上可以直接使用，app端用的也是这个版本。 你先试试，我晚些时候测试一下兼容性。

**Comment by yimik** [comment]
> implementation 'com.squareup.okhttp3:okhttp:4.7.2'
> 
> 在gradle里面引用okhttp，理论上可以直接使用，app端用的也是这个版本。 你先试试，我晚些时候测试一下兼容性。

好的，我试下

**Comment by eprendre** [comment]
经测试代码是OK的，放心使用。

**Comment by yimik** [comment]
> 经测试代码是OK的，放心使用。

确实可用👍
只不过到最后一步，嗅探不出资源，功亏一篑🤣
