### ISSUE TITLE
自定义外部源下载失败 下载好了复制到听书app文件夹下的files/jars目录也不会加载

### ISSUE THREAD

**Issue by LFYG** [eprendre/tingshu#36]
感觉新版耗电高很多 就下载几个2.0.x 和 1.9.x的 版本测试  结果 自定义外部源老是提示下载失败 下载好了复制到/Android/data/com.github.eprendre.tingshu/files/jars/目录也不会加载 这是啥原因造成的

**Comment by eprendre** [comment]
这些源只支持最新版。关于耗电新版也没加啥东西，也许和你播放的资源格式有关。

**Comment by eprendre** [comment]
我想起来还有一个可能性： 部分源在播放页含有广告，应站长的要求：点击播放页右上角的 `关闭广告` 不能关闭广告内容，而是隐藏起来。。。那样能提高人家网页的打开时间，好像是对他们的广告有帮助。 总之碰到这种源不要在播放页按home键切出或者直接锁屏，平时尽可能的关掉播放页收听。

**Comment by LFYG** [comment]
不是啊 最新版 也出现这问题啊 我把旧得卸载 安装新版 还是无法加载源 只有一个默认的 我复制https://eprendre2.coding.net/p/tingshu/d/tingshu/git/raw/master/TingShuSources/external_sources.json 或别的源 下载 一样提示 [外部源下载失败 ]  如果把app数据全部清除 在卸载 安装新版 就会出现 无法加载外部源  以前没有内置源 就是空的 有内置源了 有显示一个内置源 然后根据主页的那些源 地址复制进去 点确认 就提示 外部源下载失败 我从1.5.x用到现在 从更新出外部源开始所有版本都有这问题 只是我没问出来 因为有时候 安装完就会直接加载外部源 有源的情况下 下次更新 直接覆盖更新就没事 如果卸载完在更新 八成以上会无法加载源

**Comment by LFYG** [comment]
而且 下载好的那个 jar格式的源文件 复制到 /Android/data/com.github.eprendre.tingshu/files/jars/ 目录 也不会加载 最新版 最新源 测试 现在彻底无法用了

**Comment by eprendre** [comment]
估计你的手机是oppo 或者vivo，安卓5 。 那时候ov系统安卓5 实际上魔改自4.4。
app 使用了一个叫 Fuel 的库来处理网络请求，比如下载源。然后我发现 Fuel 不支持安卓 4.4，最低要求5，于是我就把最低安装限制改为了安卓5。。。但架不住某些系统魔改自4.4。 
关于jar包，你放到哪个目录之后需要彻底重启app才行。

**Comment by eprendre** [comment]
我只能说你这系统有问题，能刷就刷上去吧。😭 安卓5.1我虚拟机测试都 OK 的。

**Comment by LFYG** [comment]
今天突然想起 以前全新安装 要把手机关机重启下 在安装 就能更新外部源了 感觉是有啥权限没取得成功 （可能是读写文件权限 因为 以前以遇到过 把缓存设置为外置存储卡 可以听书 但缓存的文件不知道存哪去了 外置存储 没有缓存文件 ）  因为我没重启手机之前 和昨天一样 内置更新也是下载失败 无法读取复制到jars目录的下载好的源文件  而我把软件卸载后 把手机关机重启后 在安装 打开后外部源就自动更新了 别的源也能下载了 手动复制的源 放到jars目录也能读取成功了  特意卸载安装 测试了好几回 只要把手机关机重启后在安装 就没问题 最后 备注下 小米的 安卓 5.1.1原版系统 没root过  可以把这个关闭了

**Comment by eprendre** [comment]
🤔还真可能是系统问题，因为你这么一说我想起了有部分用户不敢用内置更新，否则会出现奇怪的问题需要重启手机才行。他们通过网盘下载再安装更新却没事。多发生老的手机上，这东西和权限没啥关系，app使用的那几个目录都是不需要权限的。 搞不清楚具体原因，有点玄学。

**Comment by LFYG** [comment]
昨天用网页听了一下午 但下一级时灵时不灵 后来想起隔壁还有个app 就去试了下 结果22无法用  然后今天其实我是打算把你以前老版源码里面的源看看能不能修复下将就着用的 结果打开网盘找备份的源码 看见备份的旧版app文件夹里面有个自己备注的文件 打开后看见是以前用时 遇到的一些问题解决方法 才想起来  这回记录在这 省的以后忘了
