### ISSUE TITLE
加载不了源

### ISSUE THREAD

**Issue by dotfeng** [eprendre/tingshu#37]
honor v20,android 10,

版本2.1.6

添加推荐的订阅源提示下载失败，挂代理也下载失败，手动下载jar包放到固定目录中，也没加载。

![](https://i.imgur.com/OVmSlKV.jpg)

![](https://i.imgur.com/T09w8b1.jpg)  

![](https://i.imgur.com/OtytnSo.jpg)

**Comment by eprendre** [comment]
试一下重启手机

**Comment by dotfeng** [comment]
重启手机好了，也可以添加订阅源了。:+1:
