### ISSUE TITLE
喜马拉雅VIP登录后不能播放VIP书籍

### ISSUE THREAD

**Issue by allegiant** [eprendre/tingshu#38]
抓包发现用本app播时使用的是s1.xmcdn.com，不能正常播放；
用网页版播放时使用的是audiopay.cos.tx.xmcdn.com,正常播放；

**Comment by eprendre** [comment]
s1.xmcdn.com 我去搜了一下，都是js，html的地址，确定是播放地址吗？如果有完整的扔出来参考一下。
登录后不能播放可以去试试设置默认浏览器为系统内置的浏览器，有人说这么做解决了。或者尝试升级 WebView 到最新稳定版。

**Comment by allegiant** [comment]
未找到原因
