### ISSUE TITLE
请问软件本体的源码能开源吗？想学习一下

### ISSUE THREAD

**Issue by popyang** [eprendre/tingshu#39]
请问软件本体的源码能开源吗？想学习一下

**Comment by eprendre** [comment]
曾经发生过有人拿着我开源的代码跑去市场上架/(ㄒoㄒ)/~~
其实也没啥好看的，本体只是UI方面的代码，有经验的安卓开发者拿着app看一眼界面都能自己做出来一个，甚至做的比我的还要好看。然后核心的解析代码你也看到了，我这里是开源的。
