### ISSUE TITLE
666

### ISSUE THREAD

**Issue by GuanguangT** [eprendre/tingshu#4]
App不错，很有用
说真的，很希望开发者能把主页面改成书架（收藏），
有几个原因吧
首先，多数情况下我们不可能只听一本书，基本上都是每次添加多本书一起听（比如我，天一黑基本不会听灵异，盗墓..这类，，）
另外就是，虽然主页有个继续收听按钮，但是真没必要每次打开都会直接进去书城，书城一般只有找小说才会进去
先这样吧，就想到这么多

**Comment by eprendre** [comment]
嗯很有道理, 但是我一开始代码没这么设计, 得花点时间去重构一下。

**Comment by eprendre** [comment]
搞定
