### ISSUE TITLE
鸿蒙OS音乐无缝切换

### ISSUE THREAD

**Issue by leonwahy** [eprendre/tingshu#40]
您好！
刚更新了鸿蒙OS2，目前还无法被自带的音乐无缝切换功能集成。
不知道能否实现，让其音乐无缝切换功能集成。
如果需要鸿蒙官方调整，请忽略。谢谢！

**Comment by eprendre** [comment]
我用的也是鸿蒙，更新当天我也有这个疑惑。去找了不少资料还是没有头绪，估计需要官方主动兼容吧。

**Comment by leonwahy** [comment]
OK，谢谢！
