### ISSUE TITLE
喜马拉雅付费专辑听不了啦！已登录会员账号

### ISSUE THREAD

**Issue by EatmeIon** [eprendre/tingshu#41]

**Comment by eprendre** [comment]
原因一直未知，有人清除了系统应用里的WebView数据就好了。也有升级了WebView解决的。如果前者都不行估计就没办法了

**Comment by EatmeIon** [comment]
> 原因一直未知，有人清除了系统应用里的WebView数据就好了。也有升级了WebView解决的。如果前者都不行估计就没办法了

这就很尴尬了，之前听着听着就不行了，不会缓存新的章节
Android System WebView升级到94.0.4606.31也不行
清除全部数据也不行
