### ISSUE TITLE
穿山甲广告bug

### ISSUE THREAD

**Issue by 477677074** [eprendre/tingshu#42]
首先声明，**并不是阻止开发者添加广告**。
问题描述：

在播放界面弹出视频广告时播放声音出现问题。

可能原因：
1. 同一扬声器收到两部分音源，尽管广告音源禁音但是音源仍然存在，导致bug。
2. 穿山甲视频广告bug
3. 播放器兼容问题（存疑）

可能的解决方法：
1. ban广告类型中的**视频广告**

是否因为机型或系统原因导致偶发性bug：未知

**机型：YAL-AL00**
**系统：HarmonyOS 2.0**

问题原因及解决办法只是猜测，对于我本人使用微乎其微block请求即可，但可能会对一些用户产生影响，**还请作者修正，多谢**

**Comment by eprendre** [comment]
收到，谢谢反馈。我自己不用有广告的源所以测试不到位。

**Comment by eprendre** [comment]
我用自己手机测试了一下，弹出视频广告时音频会出现短暂的暂停并立即继续播放。不知你说的是否属于这个情况。针对这个情况我做一下解释：安卓有个东西叫音频焦点。我的app对音频焦点做了处理：当丢失音频焦点时自动暂停，恢复焦点时自动继续播放。比如打电话->挂电话。当视频广告出现时获取了音频焦点又立即释放掉了，这种问题不大。如果是其它问题请详细描述一下。
功能相关：app 设置里有一个[忽略其它app的音频焦点]，可以去那边微调一下。

**Comment by 477677074** [comment]
> 我用自己手机测试了一下，弹出视频广告时音频会出现短暂的暂停并立即继续播放。不知你说的是否属于这个情况。针对这个情况我做一下解释：安卓有个东西叫音频焦点。我的app对音频焦点做了处理：当丢失音频焦点时自动暂停，恢复焦点时自动继续播放。比如打电话->挂电话。当视频广告出现时获取了音频焦点又立即释放掉了，这种问题不大。如果是其它问题请详细描述一下。
> 功能相关：app 设置里有一个[忽略其它app的音频焦点]，可以去那边微调一下。

我使用的是普通模式，我出现的问题是在播放到视频广告时软件声音变小，音质变差，录屏发现广告声音也被录制了进去，这说明在播放音频时广告也是在同时播放的，只是用户听不到这一部分，只能听到软件播放的音频，但是两段音频时同时输出的。
在网上查了一下，发现可能也和硬件有关系，如果说您测试发现没有问题，其他用户也没有反馈的话这个问题其实也就可以忽略了，对于我个人其实几乎没有影响，多谢

https://user-images.githubusercontent.com/64297564/132291772-878907fb-ec96-4756-905f-a3177388fa67.mp4

**Comment by eprendre** [comment]
了解，我多测试测试。
