### ISSUE TITLE
如何同时搜索几个订阅源？

### ISSUE THREAD

**Issue by wingmancn** [eprendre/tingshu#48]
以前可以一次搜索就能在所有订阅源中搜索
后来改了，只能一次搜索一个订阅源，反倒更麻烦
![This is an image](https://s3.xoimg.com/i/2022/03/30/j1bboo.png)
能改一下吗，我想同时“听书源”和网友制作的订阅源中搜索（比如鸽子制作的“写源不易”），不用每次切换再搜索一次

**Comment by eprendre** [comment]
我知道会麻烦一点，但也是为以后考虑。鸽子源一直没维护，相当于已经废了。现在随着订阅源越来越多，如果还像以前那样全部搜一遍影响很不好。

**Comment by wingmancn** [comment]
明白了，那只好这样了，谢谢回复
