### ISSUE TITLE
大佬，这里有一个关于"酷我"源的问题

### ISSUE THREAD

**Issue by Vampire147** [eprendre/tingshu#49]
"我的听书“在搜索书名的时候很多”酷我畅听“的有声书都搜不到。

我下载了一个他们的app看了一下，这些搜不到的大部分都是2-3个月前更新的那些。

大佬您能不能帮忙看看？？

**Comment by eprendre** [comment]
你应该直接告诉我具体书名，我找了半天才找到一本3月份上架的书。。。我的听书是可以搜到的，但是呢聚合搜索只取第一页结果，想要看到更全的结果你需要单独长按酷我源搜。

**Comment by Vampire147** [comment]
好的好的，麻烦您了，

我找了一些列子： 

洪荒：阐教首徒         主播：播音半山

大佬，如果您需要调试的话，好像有一个叫 “飞卢听书” 的主播里面有十几本都没有办法搜到，所以应该比较集中一点。里面的从2021年十二月到今天上传的好像很多都搜不到。

**Comment by Vampire147** [comment]
当然，这些书在您的app中是可以在“喜马拉雅”与“懒人听书”这两个源里搜得到的，这很棒。
只不过他们都需要各自独有的VIP才可以收听。

**Comment by eprendre** [comment]
我去抓了一下酷我畅听的接口，发现和我目前用的不太一样。其实我并没有破解能力，所用酷我接口也是网友给我的。我猜测可能是老版本的接口，一旦这个接口失效我也无法修复，且用且珍惜吧。搜了几本飞卢听书的小说，除了洪荒：阐教首徒没搜到，其它倒是都可以找到。
