### ISSUE TITLE
CPU占用奇高？

### ISSUE THREAD

**Issue by EatmeIon** [eprendre/tingshu#51]
就算后台什么也不干，不播放任何内容CPU占用都能怼到70％左右？动不动还能破100％+？

**Comment by eprendre** [comment]
有人也在群里反馈cpu占用率过高的问题，经他自己反复排查是因为他加了去广告hosts导致的。我猜测是广告组件请求不成功，便一直在重试从而引发cpu使用率过高。恳请大家不要做各种骚操作，比如禁用app的各种组件、修改hosts等。
