### ISSUE TITLE
定时关闭后还是在唤醒手机

### ISSUE THREAD

**Issue by buzenm** [eprendre/tingshu#52]
晚上睡觉前设置定时关闭后，晚上待机会导致额外耗电，电量使用情况显示手机一直在保持唤醒，miui13

**Comment by eprendre** [comment]
设置打开：定时关闭是否完全退出。

**Comment by buzenm** [comment]
试了，没用

**Comment by eprendre** [comment]
是否在播放页直接锁屏了？

**Comment by eprendre** [comment]
最主要的耗电是播放器，只要开启完全退出播放器就被干掉了。（确保通知栏不见了，如果通知栏还在说明你没有开启完全退出）。还有一个可能的耗电是部分源在播放页的广告，定时的时候按返回键关闭播放页试试，记住不是按home键退回到桌面。。

**Comment by buzenm** [comment]
试过返回桌面然后再锁屏，不行
我试试退出播放页

**Comment by buzenm** [comment]
我发现好像是miui的问题，我试了好几个播放软件都一样，aimp也是，定时关闭后还是会在后台不停唤醒

**Comment by eprendre** [comment]
嗯 可能是操作系统层面的保活，我以前用喜马拉雅、网易云。。上车连上蓝牙就自动播放，得去设置里给停止了才解决。
