### ISSUE TITLE
怎么管理书签啊？

### ISSUE THREAD

**Issue by klxq520** [eprendre/tingshu#53]
要管理添加的书签每次都得点播放按钮，再点书签按钮，能不能做到边栏或其他方便的位置啊，因为我经常要从书签里挑过去的知识重新听来巩固的，主要做学习用，望改进哈

**Comment by eprendre** [comment]
不一定是播放按钮，你从收藏、历史打开也行。目前书签跟书籍绑定的，只有打开了对应的书籍才能管理它的书签。
