### ISSUE TITLE
有开发pc版的打算吗，本地听书的功能太棒了

### ISSUE THREAD

**Issue by wanan1234** [eprendre/tingshu#56]
本地听书的功能太好用了，下载了很多mp3有声书，用音乐播放器很不方便。这个软件能记录每一本书的进度，非常棒。在pc上和ios上都没有同类的本地mp3有声书播放器，电脑听书太不方便了

**Comment by luchun0112** [comment]
> 

可以先安装个兆懿，再安装安卓版本，这样就可以在电脑上用收听了

**Comment by eprendre** [comment]
我自己测试过雷电模拟器9（其他版本可能会闪退），里面有个共享文件的功能，打通PC和模拟器的文件共享。然后app的本地书库只要指定这个共享目录即可读取pc上的文件，非常方便。 比如我PC上把音频文件丢进指定的共享目录，模拟器里把本地书库的路径设置到 /sdcard/Pictures/XXX 即可。相信其它模拟器也有类似的功能。
<img width="1169" alt="Snipaste_2022-12-13_01-29-51" src="https://user-images.githubusercontent.com/7194531/207113440-3dd6b28e-a1fb-4855-b49f-7de538e2dd4c.png">
