### ISSUE TITLE
有音频文件在本地书库可以播放，上传至webdav后无法播放

### ISSUE THREAD

**Issue by ayanami-desu** [eprendre/tingshu#61]
https://mega.nz/file/mfRkFDqZ#UUh2K472fuC71qufxXtEdq5YINQvt45ob_xj8h5NrU4
（nsfw音频文件）
我猜测这个文件经由wav转换mp3而来，但转换过程中有什么不规范的地方，因为我用格式工厂将这个文件再次转换为mp3格式后在webdav就能正常播放了。
此外，用mxplayer (smb) 能在线播放。我猜可能是您用的音频相关库有什么问题。

**Comment by eprendre** [comment]
这个文件我放WebDAV里面正常播放，可能和你的设备硬解某个参数不支持在线播放有关吧。下版本我把软解给默认开启。我用的是ExoPlayer，外加ffmpeg插件。目前已知不支持wma，其它格式应该都没问题。

另外WebDAV可以关闭文件浏览模式，以达到更好的体验:wink:。 不过需要按约定构建好目录结构。
![p](https://user-images.githubusercontent.com/7194531/236665064-df4fcf34-1375-476d-b60d-2c2e44d29d6f.jpg)

**Comment by ayanami-desu** [comment]
感谢解答

**Comment by ayanami-desu** [comment]
另外请问一下smb局域网共享要怎么正确设置？我在电脑、手机上的solid explorer上都能正常使用smb，唯独在这个软件上不行。
