### ISSUE TITLE
是否能支持abs刮削文件的识别

### ISSUE THREAD

**Issue by xuange-dada** [eprendre/tingshu#62]
emby可以识别有声书书的刮削以实现类似电影海报墙的效果，包含书本信息，本软件是否能支持呢

**Comment by FanchangWang** [comment]
刮削其实就是通过音视频的文件名或者附带信息里的音乐/电影名字，作者，年份等信息，去一些专门的音视频信息网站（像豆瓣电影这种介绍影片信息的）去搜索匹配，然后将海报图、导演、主演、啥的一堆信息下载到本地，跟音视频文件放到一起，然后一些软件如 emby、koai 之类的会自动读取这些信息，生成电影海报墙这种东西。

**Comment by xuange-dada** [comment]
> 

https://github.com/advplyr/audiobookshelf
针对AUDIOBOOKSHELF特定的刮削方式
书籍简介
创建文本文件 desc.txt ，将书籍简介保存，编码格式请选择UTF-8，否则可能乱码，保存到音频目录

主播
创建文本文件 reader.txt ，将主播信息保存，编码格式请选择UTF-8，否则可能乱码，保存到音频目录

直接使用AUDIOBOOKSHELF编辑元数据
这个方式对于其他软件兼容性不佳，在Audiobookshelf设置中打开存储项目元数据，即可在音频目录自动生成metadata.abs文件

metadata.abs文件为纯文本格式，类似ini格式配置文件，也可复制该文件手动编辑

**Comment by xuange-dada** [comment]
> > 刮削其实就是通过音视频的文件名或者附带信息里的音乐/电影名字，作者，年份等信息，去一些专门的音视频信息网站（像豆瓣电影这种介绍影片信息的）去搜索匹配，然后将海报图、导演、主演、啥的一堆信息下载到本地，跟音视频文件放到一起，然后一些软件如 emby、koai 之类的会自动读取这些信息，生成电影海报墙这种东西。
> 
> 感谢解惑，为啥用这么奇怪的叫法。。不就是爬虫嘛o(╥﹏╥)o 另外abs是什么玩意儿



> > 刮削其实就是通过音视频的文件名或者附带信息里的音乐/电影名字，作者，年份等信息，去一些专门的音视频信息网站（像豆瓣电影这种介绍影片信息的）去搜索匹配，然后将海报图、导演、主演、啥的一堆信息下载到本地，跟音视频文件放到一起，然后一些软件如 emby、koai 之类的会自动读取这些信息，生成电影海报墙这种东西。
> 
> 感谢解惑，为啥用这么奇怪的叫法。。不就是爬虫嘛o(╥﹏╥)o 另外abs是什么玩意儿

https://github.com/advplyr/audiobookshelf
针对AUDIOBOOKSHELF特定的刮削方式
书籍简介
创建文本文件 desc.txt ，将书籍简介保存，编码格式请选择UTF-8，否则可能乱码，保存到音频目录

主播
创建文本文件 reader.txt ，将主播信息保存，编码格式请选择UTF-8，否则可能乱码，保存到音频目录

直接使用AUDIOBOOKSHELF编辑元数据
这个方式对于其他软件兼容性不佳，在Audiobookshelf设置中打开存储项目元数据，即可在音频目录自动生成metadata.abs文件

metadata.abs文件为纯文本格式，类似ini格式配置文件，也可复制该文件手动编辑

**Comment by eprendre** [comment]
这东西适合self-hosted server, 或者打造一个媒体库用。用途和咱这app不一样吧，而且抓的网站基本上已经有这些信息了。
