### ISSUE TITLE
本地书源出现不可播放的问题

### ISSUE THREAD

**Issue by ayanami-desu** [eprendre/tingshu#64]
加载一段时间后出现错误页面，显示”当前网址解析出错了，点击重试，（有时候需要多试几次才能成功“。据我排查，应该是目录中含有txt文件就会出现这样的错误，移除txt文件后正常。我不明白本地书源为什么会出现所谓网络错误。

**Comment by ayanami-desu** [comment]
我把txt文件中的链接删去后也能正常播放。

**Comment by eprendre** [comment]
很久以前做的一个功能，可以解析txt文本格式要求为： `章节名&&播放地址` 举例：
```
CCTV-1 综合&&https://cctvtxyh5c.liveplay.myqcloud.com/live/cdrmcctv1_1/index.m3u8
CCTV-2 财经&&https://cctvtxyh5c.liveplay.myqcloud.com/live/cdrmcctv2_1/index.m3u8
CCTV-3 综艺&&https://cctvtxyh5c.liveplay.myqcloud.com/live/cdrmcctv3_1/index.m3u8
```
如果没有&&符号，直接放一个链接也是可以的，链接需要返回上方格式的文本，此举方便远程修改。

目前开启文件浏览模式时不会解析txt，感觉解析txt这功能现在没啥人用了，而且自定义直播源可以平替，我下版本加个开关吧，默认给关掉。

**Comment by ayanami-desu** [comment]
>目前开启文件浏览模式时不会解析txt
我用的就是文件浏览模式

**Comment by eprendre** [comment]
😅 刚看了代码 是我记错了，下版本一定去掉。我在等阿里云盘的一个接口，官方说8月份会加，到时候有了app马上更新。

**Comment by ayanami-desu** [comment]
那我关掉issue了

**Comment by ayanami-desu** [comment]
不知是否可以问一下更新计划

**Comment by eprendre** [comment]
阿里云那个接口现在又说不加了，我在想其它方法。你加群或者频道，我直接给你打包一个吧。
