### ISSUE TITLE
建议搜索一次性搜索所有站点

### ISSUE THREAD

**Issue by qstdnx** [eprendre/tingshu#7]
像点心听书和这个差不多，只有三个站点，但是没有加速。搜索是一次新搜索全部站点的。
加速希望能更快，因为读的实在太慢，至少4倍速希望能达到。之前用点心都是下载下来用其他软件加速听有点麻烦。大哥全靠你了，要捐赠什么的尽管说（ '▿ ' ）跪谢。

**Comment by eprendre** [comment]
没问题，说的两点都能做。
 不过你确定4倍速吗？我光是2倍速就不行了😱

**Comment by qstdnx** [comment]
> 没问题，说的两点都能做。
> 不过你确定4倍速吗？我光是2倍速就不行了😱

不设上限最好（上限尽量高点）
我听书速度是一点一点加快的，最早用anyview慢慢加到2~3倍，后来用阅读星支持一点一点加，从70速慢慢加到90左右（阅读星加速不是按倍速算的），后来老版本讯飞语音加到4倍速，我也不知道人类的极限在哪。主要是因为看小说比较急着想知道后面发展，因为眼睛看比听快，听着听着等不及了就直接眼睛看了，所以听得时候只能不停的加速，之前在听书神器评论区遇到一个听得和我差不多速度的老哥Ծ ̮ Ծ

**Comment by eprendre** [comment]
🐮🍺 最近比较忙, 等有时间把功能都给加上。

**Comment by eprendre** [comment]
搞定
