### ISSUE TITLE
不自动换集的问题

### ISSUE THREAD

**Issue by libykk** [eprendre/tingshu#9]
用的mate10Pro(不知道其他安卓手机有没有这个问题)，存在息屏状态下带耳机听一整集后，不会自动切换到下一集的问题，需要唤醒屏幕(并且此时在播放页面)才会继续播放下一集。

**Comment by eprendre** [comment]
后台白名单是否都已经加了？

**Comment by eprendre** [comment]
我找到这样一个网址，先试试按照里面的来做：https://blog.csdn.net/csdn_aiyang/article/details/89250278

**Comment by eprendre** [comment]
最新 1.2.1 版本应该解决了这个问题
